id: A06367672
title: ยง5
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:51:10.533515
  last_modified_at: 2022-03-01 21:51:10.533520
