id: A06367672
title: Colophon
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:51:10.485564
  last_modified_at: 2022-03-01 21:51:10.485567
